#:schema node_modules/wrangler/config-schema.json
name = "kapadiya-net"
compatibility_flags = [ "nodejs_compat", "fetch_legacy_url" ]
compatibility_date = "2024-06-03"
pages_build_output_dir = "./dist"